version: 2.0
jobs:
  build_gcc_latest:
    docker:
      - image: circleci/ruby:stretch
    steps:
      - checkout
      - run:
          name: Set up
          command: |
            sudo apt-get update
            git submodule sync; git submodule update --init # initialize git submodules
            wget -qO- https://get.haskellstack.org/ | sh
            sudo apt-get install freeglut3 freeglut3-dev
            stack setup
            stack build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_gcc_latest
